---
- block:

  - name: Upgrade host
    ovirt_hosts:
      auth: "{{ ovirt_auth }}"
      name: "{{ item.name }}"
      state: upgraded
      check_upgrade: "{{ check_upgrade }}"
      timeout: "{{ upgrade_timeout }}"
    register: host_upgraded
